# Generated by Django 4.2.21 on 2025-10-11 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticsdashboard',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='analyticsdashboard',
            name='shared_with',
        ),
        migrations.RemoveField(
            model_name='analyticsevent',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='analyticsexport',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='analyticsreport',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='analyticswidget',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='AnalyticsAlert',
        ),
        migrations.DeleteModel(
            name='AnalyticsDashboard',
        ),
        migrations.DeleteModel(
            name='AnalyticsEvent',
        ),
        migrations.DeleteModel(
            name='AnalyticsExport',
        ),
        migrations.DeleteModel(
            name='AnalyticsReport',
        ),
        migrations.DeleteModel(
            name='AnalyticsWidget',
        ),
    ]
