# Generated by Django 4.2.21 on 2025-10-17 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_productimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0002_remove_analyticsdashboard_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('layout_config', models.JSONField(default=dict)),
                ('refresh_interval', models.IntegerField(default=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_products_sold', models.IntegerField(default=0)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('new_customers', models.IntegerField(default=0)),
                ('returning_customers', models.IntegerField(default=0)),
                ('cod_orders', models.IntegerField(default=0)),
                ('online_orders', models.IntegerField(default=0)),
                ('cod_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('online_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pending_orders', models.IntegerField(default=0)),
                ('confirmed_orders', models.IntegerField(default=0)),
                ('shipped_orders', models.IntegerField(default=0)),
                ('delivered_orders', models.IntegerField(default=0)),
                ('cancelled_orders', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('widget_type', models.CharField(choices=[('metric', 'Metric Card'), ('chart', 'Chart'), ('table', 'Data Table'), ('gauge', 'Gauge'), ('progress', 'Progress Bar'), ('text', 'Text Widget')], max_length=20)),
                ('chart_type', models.CharField(blank=True, choices=[('line', 'Line Chart'), ('bar', 'Bar Chart'), ('pie', 'Pie Chart'), ('doughnut', 'Doughnut Chart'), ('area', 'Area Chart'), ('scatter', 'Scatter Plot')], max_length=20, null=True)),
                ('data_source', models.CharField(max_length=100)),
                ('query_filters', models.JSONField(default=dict)),
                ('aggregation_type', models.CharField(default='sum', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('width', models.IntegerField(default=6)),
                ('height', models.IntegerField(default=4)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('color_scheme', models.CharField(default='default', max_length=50)),
                ('show_legend', models.BooleanField(default=True)),
                ('show_grid', models.BooleanField(default=True)),
                ('refresh_interval', models.IntegerField(default=300)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='analytics.analyticsdashboard')),
            ],
            options={
                'ordering': ['position_y', 'position_x'],
            },
        ),
        migrations.CreateModel(
            name='ProductAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('page_views', models.IntegerField(default=0)),
                ('add_to_cart_count', models.IntegerField(default=0)),
                ('purchase_count', models.IntegerField(default=0)),
                ('units_sold', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('view_to_cart_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cart_to_purchase_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('view_to_purchase_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'ordering': ['-date', '-revenue'],
                'unique_together': {('product', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CustomerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('page_views', models.IntegerField(default=0)),
                ('sessions', models.IntegerField(default=0)),
                ('time_on_site', models.IntegerField(default=0)),
                ('orders_count', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('products_viewed', models.IntegerField(default=0)),
                ('products_added_to_cart', models.IntegerField(default=0)),
                ('products_purchased', models.IntegerField(default=0)),
                ('segment', models.CharField(choices=[('new', 'New Customer'), ('regular', 'Regular Customer'), ('vip', 'VIP Customer'), ('at_risk', 'At Risk'), ('inactive', 'Inactive')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-total_spent'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('product_view', 'Product View'), ('add_to_cart', 'Add to Cart'), ('remove_from_cart', 'Remove from Cart'), ('checkout_start', 'Checkout Started'), ('purchase', 'Purchase'), ('search', 'Search'), ('category_view', 'Category View'), ('user_login', 'User Login'), ('user_register', 'User Registration'), ('newsletter_signup', 'Newsletter Signup'), ('contact_form', 'Contact Form'), ('custom', 'Custom Event')], max_length=50)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('page_url', models.URLField(blank=True, max_length=500, null=True)),
                ('page_title', models.CharField(blank=True, max_length=200, null=True)),
                ('referrer', models.URLField(blank=True, max_length=500, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(blank=True, max_length=200, null=True)),
                ('product_category', models.CharField(blank=True, max_length=100, null=True)),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='analytics_a_event_t_6c35be_idx'), models.Index(fields=['user', 'created_at'], name='analytics_a_user_id_ecb128_idx'), models.Index(fields=['session_id', 'created_at'], name='analytics_a_session_533ea7_idx')],
            },
        ),
    ]
