# Generated by Django 4.2.21 on 2025-10-05 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0008_delete_fraudcheck'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryHeatmapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_sales', models.IntegerField(default=0)),
                ('total_restocks', models.IntegerField(default=0)),
                ('stock_level', models.IntegerField(default=0)),
                ('sales_velocity', models.FloatField(default=0.0, help_text='Sales per day')),
                ('turnover_rate', models.FloatField(default=0.0, help_text='How quickly stock turns over')),
                ('stagnation_score', models.FloatField(default=0.0, help_text='Higher = more stagnant')),
                ('heatmap_intensity', models.FloatField(default=0.0, help_text='0-1 scale for heatmap color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heatmap_data', to='products.product')),
            ],
            options={
                'verbose_name': 'Heatmap Data',
                'verbose_name_plural': 'Heatmap Data',
                'ordering': ['-date'],
                'unique_together': {('product', 'date')},
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('sale', 'Sale'), ('restock', 'Restock'), ('return', 'Return'), ('adjustment', 'Adjustment'), ('damage', 'Damage')], max_length=20)),
                ('quantity_change', models.IntegerField(help_text='Positive for restock, negative for sale')),
                ('stock_before', models.IntegerField(help_text='Stock level before this movement')),
                ('stock_after', models.IntegerField(help_text='Stock level after this movement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='products.product')),
            ],
            options={
                'verbose_name': 'Inventory Movement',
                'verbose_name_plural': 'Inventory Movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductPerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_sales', models.IntegerField(default=0)),
                ('sales_velocity', models.FloatField(default=0.0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_stock_level', models.FloatField(default=0)),
                ('stock_turnover', models.FloatField(default=0)),
                ('days_in_stock', models.IntegerField(default=0)),
                ('is_fast_moving', models.BooleanField(default=False)),
                ('is_slow_moving', models.BooleanField(default=False)),
                ('is_stagnant', models.BooleanField(default=False)),
                ('heatmap_color', models.CharField(default='#ffffff', help_text='Hex color for heatmap', max_length=7)),
                ('intensity_score', models.FloatField(default=0.0, help_text='0-1 scale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Performance',
                'verbose_name_plural': 'Product Performance Metrics',
                'ordering': ['-period_end'],
            },
        ),
        migrations.DeleteModel(
            name='StockTransaction',
        ),
    ]
