# Generated by Django 4.2.21 on 2025-10-11 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productimage'),
        ('inventory', '0002_inventoryheatmapdata_inventorymovement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='order',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productperformancemetrics',
            name='product',
        ),
        migrations.DeleteModel(
            name='InventoryHeatmapData',
        ),
        migrations.DeleteModel(
            name='InventoryMovement',
        ),
        migrations.DeleteModel(
            name='ProductPerformanceMetrics',
        ),
    ]
