# Generated by Django 4.2.21 on 2025-10-04 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fraud_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fraud_checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_checked_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='fraud_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='fraud_override_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fraud_override_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_override_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='fraud_override_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fraud_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fraud_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='is_flagged_fraud',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='PathaoOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathao_order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('pathao_consignment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pathao_status', models.CharField(choices=[('pending', 'Pending'), ('pickup_requested', 'Pickup Requested'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('pathao_response', models.JSONField(blank=True, default=dict)),
                ('last_status_check', models.DateTimeField(blank=True, null=True)),
                ('tracking_code', models.CharField(blank=True, max_length=100, null=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_sent_to_pathao', models.BooleanField(default=False)),
                ('send_attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pathao_order', to='orders.order')),
            ],
            options={
                'verbose_name': 'Pathao Order',
                'verbose_name_plural': 'Pathao Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FraudCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fraud', models.BooleanField(default=False)),
                ('fraud_reason', models.CharField(blank=True, choices=[('suspicious_address', 'Suspicious Address'), ('multiple_orders', 'Multiple Orders Same Details'), ('payment_issue', 'Payment Issue'), ('blacklisted_phone', 'Blacklisted Phone Number'), ('manual_flag', 'Manually Flagged'), ('automated_system', 'Automated System Detection'), ('customer_complaint', 'Customer Complaint')], max_length=50, null=True)),
                ('fraud_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_manually_overridden', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True, null=True)),
                ('overridden_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_checks_performed', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_checks', to='orders.order')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fraud Check',
                'verbose_name_plural': 'Fraud Checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourierLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('order_created', 'Order Created'), ('status_updated', 'Status Updated'), ('webhook_received', 'Webhook Received'), ('api_call', 'API Call'), ('error', 'Error'), ('manual_update', 'Manual Update')], max_length=50)),
                ('message', models.TextField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pathao_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='orders.pathaoorder')),
            ],
            options={
                'verbose_name': 'Courier Log',
                'verbose_name_plural': 'Courier Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
