# Generated by Django 4.2.21 on 2025-10-04 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_invoice_invoicetemplate_invoicelog_invoiceitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteadfastOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steadfast_consignment_id', models.CharField(blank=True, help_text='Steadfast consignment ID', max_length=100, null=True)),
                ('steadfast_status', models.CharField(default='pending', help_text='Current delivery status', max_length=50)),
                ('steadfast_response', models.JSONField(default=dict, help_text='Full API response from Steadfast')),
                ('tracking_code', models.CharField(blank=True, max_length=100, null=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery', models.DateTimeField(blank=True, null=True)),
                ('is_sent_to_steadfast', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_check', models.DateTimeField(blank=True, null=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cod_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='steadfast_order', to='orders.order')),
            ],
            options={
                'verbose_name': 'Steadfast Order',
                'verbose_name_plural': 'Steadfast Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='courierlog',
            name='pathao_order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.DeleteModel(
            name='PathaoOrder',
        ),
        migrations.AddField(
            model_name='courierlog',
            name='steadfast_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='orders.steadfastorder'),
        ),
    ]
