# Generated by Django 4.2.21 on 2025-10-04 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_steadfastorder_remove_courierlog_pathao_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fraudcheck',
            name='checked_by',
        ),
        migrations.RemoveField(
            model_name='fraudcheck',
            name='order',
        ),
        migrations.RemoveField(
            model_name='fraudcheck',
            name='overridden_by',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='order',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoicelog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='invoicelog',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceTemplate',
        ),
        migrations.RemoveField(
            model_name='steadfastorder',
            name='order',
        ),
        migrations.AlterModelOptions(
            name='courierlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveField(
            model_name='courierlog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='courierlog',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='courierlog',
            name='message',
        ),
        migrations.RemoveField(
            model_name='courierlog',
            name='request_data',
        ),
        migrations.RemoveField(
            model_name='courierlog',
            name='response_data',
        ),
        migrations.RemoveField(
            model_name='courierlog',
            name='status_code',
        ),
        migrations.RemoveField(
            model_name='courierlog',
            name='steadfast_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fraud_checked_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fraud_checked_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fraud_override',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fraud_override_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fraud_override_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fraud_override_reason',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fraud_score',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='courierlog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courier_logs', to='orders.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='pathao_order_id',
            field=models.CharField(blank=True, db_index=True, help_text='Pathao courier order ID', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pathao_response',
            field=models.JSONField(blank=True, help_text='Raw latest response from Pathao API', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pathao_status',
            field=models.CharField(blank=True, help_text='Latest status from Pathao', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courierlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create Order'), ('status', 'Refresh Status'), ('webhook', 'Webhook'), ('error', 'Error')], max_length=32),
        ),
        migrations.AlterField(
            model_name='courierlog',
            name='raw_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='FraudCheck',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
        migrations.DeleteModel(
            name='InvoiceLog',
        ),
        migrations.DeleteModel(
            name='SteadfastOrder',
        ),
    ]
