# Generated by Django 4.2.21 on 2025-10-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_fraudcheck_checked_by_remove_fraudcheck_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pathao_invoice_url',
            field=models.CharField(blank=True, help_text='Pathao invoice URL or reference', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='courierlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create Order'), ('status', 'Refresh Status'), ('invoice', 'Generate Invoice'), ('webhook', 'Webhook'), ('error', 'Error')], max_length=32),
        ),
    ]
