# Generated by Django 4.2.21 on 2025-10-05 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0006_add_pathao_invoice_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('clean', 'Clean'), ('suspicious', 'Suspicious'), ('fraud', 'Fraud'), ('error', 'Error')], default='clean', max_length=20)),
                ('risk_score', models.FloatField(blank=True, help_text='Risk score from 0-100', null=True)),
                ('fraud_reason', models.TextField(blank=True, help_text='Reason for fraud detection', null=True)),
                ('steadfast_response', models.JSONField(blank=True, help_text='Raw response from Steadfast API', null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes from admin', null=True)),
                ('checked_by', models.ForeignKey(blank=True, help_text='Admin user who performed the check', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fraud_checks', to='orders.order')),
            ],
            options={
                'verbose_name': 'Fraud Check',
                'verbose_name_plural': 'Fraud Checks',
                'ordering': ['-checked_at'],
            },
        ),
    ]
