# Generated by Django 4.2.21 on 2025-10-05 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_fraudcheck'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FraudCheck',
        ),
    ]
