# Generated by Django 4.2.21 on 2025-10-05 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_delete_fraudcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathaoStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(help_text='Pathao store ID', max_length=64, unique=True)),
                ('store_name', models.CharField(max_length=255)),
                ('store_address', models.TextField()),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=20)),
                ('secondary_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('city_id', models.IntegerField(help_text='Pathao city ID')),
                ('zone_id', models.IntegerField(help_text='Pathao zone ID')),
                ('area_id', models.IntegerField(help_text='Pathao area ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default_store', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default_store', 'store_name'],
            },
        ),
        migrations.AddField(
            model_name='courierlog',
            name='response_data',
            field=models.JSONField(blank=True, help_text='API response data', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fraud_indicators',
            field=models.JSONField(blank=True, help_text='List of fraud indicators detected', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fraud_score',
            field=models.IntegerField(blank=True, help_text='Fraud risk score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pathao_area_id',
            field=models.IntegerField(blank=True, help_text='Pathao area ID', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pathao_city_id',
            field=models.IntegerField(blank=True, help_text='Pathao city ID', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pathao_consignment_id',
            field=models.CharField(blank=True, db_index=True, help_text='Pathao consignment ID', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pathao_delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Delivery fee charged by Pathao', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pathao_delivery_type',
            field=models.IntegerField(blank=True, help_text='Pathao delivery type (48=Standard, 12=Express, 24=Next Day)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pathao_item_description',
            field=models.TextField(blank=True, help_text='Item description for Pathao', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pathao_item_type',
            field=models.IntegerField(blank=True, help_text='Pathao item type (1=Document, 2=Parcel, 3=Fragile)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pathao_item_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Item weight in kg', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pathao_special_instruction',
            field=models.TextField(blank=True, help_text='Special delivery instructions', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pathao_store_id',
            field=models.CharField(blank=True, help_text='Pathao store ID', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pathao_zone_id',
            field=models.IntegerField(blank=True, help_text='Pathao zone ID', null=True),
        ),
        migrations.AlterField(
            model_name='courierlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create Order'), ('status', 'Refresh Status'), ('invoice', 'Generate Invoice'), ('webhook', 'Webhook'), ('error', 'Error'), ('fraud_check', 'Fraud Check'), ('price_calculation', 'Price Calculation')], max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='pathao_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('In Transit', 'In Transit'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], help_text='Latest status from Pathao', max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='PathaoLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('city', 'City'), ('zone', 'Zone'), ('area', 'Area')], max_length=10)),
                ('location_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('parent_id', models.IntegerField(blank=True, help_text='Parent location ID (zone for area, city for zone)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['location_type', 'name'],
                'unique_together': {('location_type', 'location_id')},
            },
        ),
        migrations.CreateModel(
            name='PathaoInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=128, unique=True)),
                ('consignment_id', models.CharField(db_index=True, max_length=64)),
                ('invoice_data', models.JSONField(help_text='Complete invoice data')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/pathao/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathao_invoices', to='orders.order')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
