# Generated by Django 4.2.21 on 2025-10-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_pathaostore_courierlog_response_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathaoinvoice',
            name='order',
        ),
        migrations.DeleteModel(
            name='PathaoLocation',
        ),
        migrations.DeleteModel(
            name='PathaoStore',
        ),
        migrations.RemoveField(
            model_name='courierlog',
            name='response_data',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fraud_indicators',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fraud_score',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pathao_area_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pathao_city_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pathao_consignment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pathao_delivery_fee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pathao_delivery_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pathao_item_description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pathao_item_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pathao_item_weight',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pathao_special_instruction',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pathao_store_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pathao_zone_id',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_gateway_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('online', 'Online Payment')], default='cod', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='courierlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create Order'), ('status', 'Refresh Status'), ('invoice', 'Generate Invoice'), ('webhook', 'Webhook'), ('error', 'Error')], max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='pathao_status',
            field=models.CharField(blank=True, help_text='Latest status from Pathao', max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='PathaoInvoice',
        ),
    ]
